version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile if it's named differently
    ports:
      - 80:3000"              # Map host port 80 to container port 3000
      - "443:3000"              # Map host port 80 to container port 3000
    environment:
      NODE_ENV: production    # Set the environment variable for the application
    command: ["node", "dist/bin/www.js"]  # Command to run the application
    restart: unless-stopped   # Auto-restart policy
